### PR TITLE
Gnome Shell 45 support

### LINKED ISSUE #38: [Feature Request] Gnome 45 update
Hi, could you update the G45 version?

Reference:
https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

Thanks

### PR DESCRIPTION
**Pull request by mgalgs**
This adds support for Gnome Shell 45, and drops support for all versions pre-45.

NOTE: older versions of Gnome Shell will still be supported on the `pre-45` git branch (bugfixes only, no new features).

Big thank you to @gilbvp for his initial work on this migration!

Fixes #38

High-level summary of changes:

  - Migrated to es6 style imports [1]
  - Removed support for GS<45 [2]
  - Added default class exports in lieu of enable/disable functions [3]
  - Moved to subclassing Extension for main extension, with its associated
    helper properties/methods in lieu of extensionUtils [4]
  - Moved to subclassing ExtensionPreferences for prefs, with its
    associated helper properties/methods in lieu of extensionUtils [5]
  - Removed legacy Class syntax (Lang) [6]
  - Migrated to GLib-based Mainloop [7]
  - Use gettext from the extension module [8]
  - Migrated logging to standard console.* methods [9]
  - Migrated preferences dialog to Adwaita [10]

 [1] https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm
 [2] https://gjs.guide/extensions/upgrading/gnome-shell-45.html#shell-version
 [3] https://gjs.guide/extensions/upgrading/gnome-shell-45.html#extension-js
 [4] https://gjs.guide/extensions/upgrading/gnome-shell-45.html#extensionutils
 [5] https://gjs.guide/extensions/upgrading/gnome-shell-45.html#prefs-js
 [6] https://gjs.guide/guides/gjs/legacy-class-syntax.html#binding
 [7] https://discourse.gnome.org/t/how-to-import-mainloop-on-gnome-45-version/17605
 [8] https://gjs.guide/extensions/upgrading/gnome-shell-45.html#extensionutils
 [9] https://gjs.guide/extensions/upgrading/gnome-shell-45.html#logging
[10] https://gjs.guide/extensions/development/preferences.html#prefs-js

# Testing instructions

First, remove the extension if you already have it installed. Then something like:

```
git clone git@github.com:mgalgs/gnome-shell-system-monitor-applet.git
git checkout gs45
cd ~/.local/share/gnome-shell/extensions
ln -sv /path/to/gnome-shell-system-monitor-applet/system-monitor@paradoxxx.zero.gmail.com/
```

Then reload your session (`Alt-F2 r` under X11, logout/login under Wayland), and enable the extension using the Extensions app, or with:

```
gnome-extensions enable system-monitor-next@paradoxxx.zero.gmail.com
```

(Taken from the ["Manual Installation" section of the README.md (from this branch)](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/gs45/README.md#manual-installation)):

# TODO

- [ ] (Help wanted!) Figure out Battery issue (see comment in `Battery()`).
- [x] (Help wanted!) Fix Adwaita layout on Preferences page (no close button atm).
- [ ] (Help wanted!) Make preferences page look nicer.
- [x] Disable CI/CD until the branch split can be figured out. (Edit: actually we only push on new tags, so should be fine. I'll probably submit this first 45+ build manually so that I can see how the multi-version submission process works.)

### CODE REVIEW

**Comment by mgalgs** [comment]
> TODO:
> - [ ] Fix Adwaita layout on Preferences page (no close button atm).

So turns out that there *is* a close button, you just have to resize your window horizontally by 9 billion pixels to see it.

I've added a `Gtk.ScrolledWindow` around everything for now and that is slightly better... Still kinda glitchy (reordering tabs is bonkers, clicking stuff near the scroll edge causes an abrupt scroll, etc) but will hold us over until someone can do a broader overhaul of the preferences window.

**Comment by BxOxSxS** [comment]
Hi, I tested PR and got error `elts[elt] is undefined`. Detailed output from `journalctl -xe /usr/bin/gnome-shell`:
```
JS ERROR: Extension system-monitor-next@paradoxxx.zero.gmail.com: TypeError: elts[elt] is undefined
                                             enable@file:///home/boss/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:2455:17
                                             _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:252:38
                                             loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:461:32
                                             async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:759:24
                                             async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:765:48
                                             _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:800:20
                                             async*init@resource:///org/gnome/shell/ui/extensionSystem.js:71:14
                                             _initializeUI@resource:///org/gnome/shell/ui/main.js:291:22
                                             start@resource:///org/gnome/shell/ui/main.js:164:11
                                             @resource:///org/gnome/shell/ui/init.js:11:47
                                             @resource:///org/gnome/shell/ui/init.js:21:20
```

I am on arch linux (gnome 45 ofc). If any additional  info is needed let me know

**Comment by BxOxSxS** [comment]
> @BxOxSxS I reckon I've seen that before when I'd written a new graph and switched back to another version of the extension that didn't have it, but my settings for graph ordering were still expecting it. You could try deleting the settings keys relating to graph ordering to reset to the defaults? I'll dig up the commands to use
> 
> Edit: I'm not at my computer atm, but `dconf dump /org/gnome/shell/extensions/system-monitor/` shows all the keys, then it should be like `dconf delete <key>` or something

Thank you! I just simply reset all keys with `dconf reset -f /org/gnome/shell/extensions/system-monitor/` and it works fine now

**Comment by mgalgs** [comment]
@BxOxSxS good catch, I'm able to reproduce by re-ordering the position list. I've just added a fix for this to this branch so that you shouldn't need to do the dconf workaround in the future.

**Pull request merged**
