### PR TITLE
Use labels instead of file names for sensors (temperature, fan)

### PR DESCRIPTION
**Pull request by rschupp**
Suggested fix for #63.

The **file names** of sensor devices (e.g. `/sys/class/hwmon/hwmon4/temp1_input`) are not stable and may change on reboot (esp. when booting a different kernel). But the corresponding **labels** (e.g. `/sys/class/hwmon/hwmon4/{name,temp1_label}`) are stable. Hence we should not "remember" (ie. via settings) the file name, but the label.

This patch changes _check_sensors()_ (in `prefs.js`) to return a mapping "label → file name" instead of two parallel lists of labels and files. `pref.js` stores the label in settings and `extension.js` will read them from settings. It needs _check_sensors()_ to translate the label into a file name. Hence move _check_sensors()_ in a new common module, `common.js` and import it from both `prefs.js` and `extension.js`. Add _parse_bytearray()_ to `common.js`, too, as it's used both from `extension.js` and `common.js`.

### What I tested

- [x] Verified no regressions to existing functionality.
- [x] Tested on the following Gnome Shell versions: 45, 46

- - -
This change is [Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/73)

### CODE REVIEW

**Review by mgalgs — CHANGES_REQUESTED** [review]
This looks fantastic! Thank you for the excellent commit messages and test results. Aside from deleting the old physical device code I'd love to get test results from another user or two who was experiencing this problem.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/73#-:-NwQXmMuDPbQ5tpc98mB:bnc63p9)* status: all files reviewed, 1 unresolved discussion (waiting on @rschupp)

___
*[`system-monitor-next@paradoxxx.zero.gmail.com/common.js` line 81 at r1](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/73#-NwQidfRE9-FPDqprrfS:-NwQidfRE9-FPDqprrfT:b-dofnwp) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/d1db4a7b572363ec4a797d644346cfaab3a78125/system-monitor-next%40paradoxxx.zero.gmail.com/common.js#L81)):*
> ```JavaScript
>         if (!add_sensors_from(chip, chip_label)) {
>             // This is here to provide compatibility with previous code, but I can't find any
>             // information about sensors being stored in chip/device directory. Can we delete it?
> ```

I vote for deletion! :ballot_box: Looks like kernel drivers should have been implementing the new approach (using the hwmon "class" directory instead of the physical device directory) since lm-sensors v3.0.1, released circa 2008...

https://static.lwn.net/kerneldoc/hwmon/sysfs-interface.html
___
*[`system-monitor-next@paradoxxx.zero.gmail.com/prefs.js` line 515 at r1](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/73#-NwQk-bq08SHaE9bDYwW:-NwQk-brDv1RGWBprTf2:blxd8qb) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/d1db4a7b572363ec4a797d644346cfaab3a78125/system-monitor-next%40paradoxxx.zero.gmail.com/prefs.js#L515)):*
> ```JavaScript
> 
>                 if (labels.length === 0)
>                     stringListModel.append(_('Please install lm-sensors'));
> ```

`lm-sensors` shouldn't need to be installed in order for the sysfs files to be populated if I'm not mistaken... A better error message might be just "Error reading sensor files from sysfs". This isn't exactly related to your patch so feel free to ignore.

**Review by rschupp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/73)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @mgalgs)

___
*[`system-monitor-next@paradoxxx.zero.gmail.com/common.js` line 81 at r1](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/73#-NwQidfRE9-FPDqprrfS:-NwUwhs61nZQhhsb0Kmd:bb6un1j) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/d1db4a7b572363ec4a797d644346cfaab3a78125/system-monitor-next%40paradoxxx.zero.gmail.com/common.js#L81)):*
<details><summary><i>Previously, mgalgs (Mitchel Humpherys) wrote…</i></summary><blockquote>

I vote for deletion! :ballot_box: Looks like kernel drivers should have been implementing the new approach (using the hwmon "class" directory instead of the physical device directory) since lm-sensors v3.0.1, released circa 2008...

https://static.lwn.net/kerneldoc/hwmon/sysfs-interface.html
</blockquote></details>

Done

**Review by rschupp — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/73)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @mgalgs)

___
*[`system-monitor-next@paradoxxx.zero.gmail.com/prefs.js` line 515 at r1](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/73#-NwQk-bq08SHaE9bDYwW:-NwUxt3z4tt0pMEx6eNf:bfygclp) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/d1db4a7b572363ec4a797d644346cfaab3a78125/system-monitor-next%40paradoxxx.zero.gmail.com/prefs.js#L515)):*
<details><summary><i>Previously, mgalgs (Mitchel Humpherys) wrote…</i></summary><blockquote>

`lm-sensors` shouldn't need to be installed in order for the sysfs files to be populated if I'm not mistaken... A better error message might be just "Error reading sensor files from sysfs". This isn't exactly related to your patch so feel free to ignore.
</blockquote></details>

Done: I just changed it to just "No fan/temperature sensors found" ("sysfs" probably doesn'tmean anything for most users)

**Comment by rschupp** [comment]
@mgalgs Addressed your points and added a little cleanup.

**Comment by rschupp** [comment]
@mgalgs There's one problem left switching from sensor file paths to sensor labels: the corresponding schema entries:
```
    <key name="thermal-sensor-file" type="s">
      <default>'/sys/devices/virtual/thermal/thermal_zone0/temp'</default>
      <summary>Sensor File</summary>
      <description>Location of the sensor file for cpu temp</description>
    </key>
...
    <key name="fan-sensor-file" type="s">
      <default>'/sys/devices/virtual/thermal/cooling_device0/cur_state'</default>
      <summary>Sensor File</summary>
      <description>Location of the sensor file for fan</description>
    </key>
````
Summary and description are easily adapted, but what about the defaults? There's no reasonable default label. Note that the existing defaults are **never** listed by _check_sensors()_ as it only looks for entries below `/sys/class/hwmon/`. So while the current default (before this PR) gave you something (if the files even exist),  you didn't know what it is for. But once you used preferences you couldn't get back to this default setting (unless using `gsettings reset` or similar). So I tend to change defaults to the empty string (which means no values are shown until you make a choice in preferences).

**Comment by ixevix** [comment]
Looks like there is a missing ) in prefs.js
https://github.com/mgalgs/gnome-shell-system-monitor-applet/issues/63#issuecomment-2082747843

**Comment by rschupp** [comment]
@ixevix Thanks, fixed. Note that in [912e233](https://github.com/mgalgs/gnome-shell-system-monitor-applet/pull/73/commits/912e233c705cfcdb0af6d7d2809ecbb759545d85) I "renamed" the geschema key _thermal-sensor-file_ to _thermal-sensor-label_ (same for _fan..._) and changed the defaults to ''. So if you test after that, the extension will not show any temperatur/fan items until you choose a sensor in the preferences.

**Review by mgalgs — APPROVED** [review]
> Summary and description are easily adapted, but what about the defaults? There's no reasonable default label. Note that the existing defaults are **never** listed by _check\_sensors()_ as it only looks for entries below `/sys/class/hwmon/`. So while the current default (before this PR) gave you something (if the files even exist), you didn't know what it is for. But once you used preferences you couldn't get back to this default setting (unless using `gsettings reset` or similar). So I tend to change defaults to the empty string (which means no values are shown until you make a choice in preferences).

This sounds good.

:lgtm_strong: 

> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/73#-:-NwvPOAHEC0GYWdFEpQe:b-tzp9hy)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @rschupp)

___
*[`system-monitor-next@paradoxxx.zero.gmail.com/prefs.js` line 515 at r1](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/73#-NwQk-bq08SHaE9bDYwW:-Nwv3o85-ki7tSvP1sxH:b-8fx2u7) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/d1db4a7b572363ec4a797d644346cfaab3a78125/system-monitor-next%40paradoxxx.zero.gmail.com/prefs.js#L515)):*
<details><summary><i>Previously, rschupp (Roderich Schupp) wrote…</i></summary><blockquote>

Done: I just changed it to just "No fan/temperature sensors found" ("sysfs" probably doesn'tmean anything for most users)
</blockquote></details>

:+1:

**Comment by snowyoneill** [comment]
Pretty sure in the case of multiple nvme drives installed using the `label-filename` option results in only a single drive sensors being enumerated due to fact that there is an assumption that hwmon device names are unique ( which is not the case ) 

```
/sys/class/hwmon/hwmon0/name -> ACAD
/sys/class/hwmon/hwmon1/name -> acpitz
/sys/class/hwmon/hwmon2/name -> BAT1
/sys/class/hwmon/hwmon3/name -> nvme
/sys/class/hwmon/hwmon4/name -> nvme
```

```
/sys/class/hwmon/hwmon3/temp1_label -> Composite
/sys/class/hwmon/hwmon3/temp2_label -> Sensor 1
/sys/class/hwmon/hwmon3/temp3_label -> Sensor 2
/sys/class/hwmon/hwmon4/temp1_label -> Composite
/sys/class/hwmon/hwmon4/temp2_label -> Sensor 1
/sys/class/hwmon/hwmon4/temp3_label -> Sensor 2
```

**Pull request merged**
