### PR TITLE
Add Gnome Shell 46 support.

### PR DESCRIPTION
**Pull request by glerroo**
This close issue #61.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64)

### CODE REVIEW

**Review by mgalgs — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64)* status: all files reviewed, 3 unresolved discussions (waiting on @glerroo)

___
*[`system-monitor-next@paradoxxx.zero.gmail.com/extension.js` line 265 at r1](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64#-NsRUnZg8NgtejUam8sK:-NsRUnZg8NgtejUam8sL:b8bzkz1) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/8832b564383ea61b3f81c6972dccc344b518f958/system-monitor-next%40paradoxxx.zero.gmail.com/extension.js#L265)):*
> ```JavaScript
>             let mainContentBox = new St.BoxLayout({style_class: 'prompt-dialog-main-layout',
>                                                    vertical: false});
>             this.contentLayout.add_child(mainContentBox,
> ```

I'm still trying to understand this change. The [GS 46 extension porting guide](https://gjs.guide/extensions/upgrading/gnome-shell-46.html#clutter-container) mentions `Clutter.Container` (`Clutter.Container.add_actor` being of particular interest to us), but I'm not seeing anything about an `.add()` method going away... And I'm actually not even sure which `.add()` method is being called here. I can't find an `.add()` in the `St.BoxLayout` inheritance chain in the gjs docs but I might just be missing it. :grimacing: 
___
*[`system-monitor-next@paradoxxx.zero.gmail.com/extension.js` line 353 at r1](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64#-NsRX7G43X3qSQlYf5n9:-NsRX7G56jd5Bwj4FjhH:b7ew998) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/8832b564383ea61b3f81c6972dccc344b518f958/system-monitor-next%40paradoxxx.zero.gmail.com/extension.js#L353)):*
> ```JavaScript
>             Clutter.cairo_set_source_color(cr, this.extension._Background);
>         else
>             cr.setSourceColor(this.extension._Background);
> ```

I think this pattern is repeated enough to warrant a helper function. Something like:


```js
// Gnome 45 Clutter.cairo_set_color compatibility
function sm_cairo_set_source_color(cr, bg_color) {
    if (Clutter.cairo_set_source_color)
        Clutter.cairo_set_source_color(cr, bg_color);
    else
       cr.setSourceColor(bc_color);
}
```
___
*[`system-monitor-next@paradoxxx.zero.gmail.com/metadata.json` line 2 at r1](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64#-NsRJoq-0tuuCqIhqiGP:-NsRJoq-0tuuCqIhqiGQ:b-l98zfn) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/8832b564383ea61b3f81c6972dccc344b518f958/system-monitor-next%40paradoxxx.zero.gmail.com/metadata.json#L2)):*
> ```JSON
> {
>     "shell-version": ["45","46"],
> ```

nit: space after comma

**Review by mgalgs — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64)* status: all files reviewed, 4 unresolved discussions (waiting on @glerroo)

*[a discussion](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64#-NsRYy32EBQHABDOY9w1:-NsRYy32EBQHABDOY9w2:b8q3nzo) (no related file):*
Thanks for the patch!!!

Could you please also share which versions of GS you tested this on?

___

**Comment by marxin** [comment]
Thanks for the pull request. I noticed the following error when running (8832b564383ea61b3f81c6972dccc344b518f958) under Gnome 46:

```
Mar 08 08:48:29 kettlebell gnome-shell[2642]: Extension system-monitor-next@paradoxxx.zero.gmail.com: TypeError: Main.panel._centerBox.remove_actor is not a function
                                              
                                              Stack trace:
                                                enable@file:///home/marxin/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:2451:39
                                                _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:266:38
                                                loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:478:32
                                                async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:786:24
                                                async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:792:48
                                                _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:827:20
                                                async*init@resource:///org/gnome/shell/ui/extensionSystem.js:76:14
                                                _initializeUI@resource:///org/gnome/shell/ui/main.js:303:22
                                                start@resource:///org/gnome/shell/ui/main.js:175:11
                                                @resource:///org/gnome/shell/ui/init.js:12:47
                                                @resource:///org/gnome/shell/ui/init.js:21:20
```

**Comment by vibragiel** [comment]
Hi. I tried the changes in this PR in Gnome-Shell 46 and it's working nicely (I didn't have to apply @marxin's changes).

**Comment by marxin** [comment]
You're likely going to hit the issue once you enable "Move the Clonk" in Extension settings.

**Comment by NVieville** [comment]
Hello,

According to:

https://gjs.guide/extensions/upgrading/gnome-shell-46.html#clutter-container

The function `remove_actor` seems to have been replaced by `remove_child`.
Maybe this is the missing last thing to modify and to get a functional extension for GS 46.

Hope this will help.

Cordially,


-- 
NVieville

**Comment by marxin** [comment]
Yep, thanks, the following patch works for me:
```patch
diff --git a/system-monitor-next@paradoxxx.zero.gmail.com/extension.js b/system-monitor-next@paradoxxx.zero.gmail.com/extension.js
index 7354ddc..058f334 100644
--- a/system-monitor-next@paradoxxx.zero.gmail.com/extension.js
+++ b/system-monitor-next@paradoxxx.zero.gmail.com/extension.js
@@ -2448,7 +2448,7 @@ export default class SystemMonitorExtension extends Extension {
 
             if (this._Schema.get_boolean('move-clock')) {
                 let dateMenu = Main.panel.statusArea.dateMenu;
-                Main.panel._centerBox.remove_actor(dateMenu.container);
+                Main.panel._centerBox.remove_child(dateMenu.container);
                 Main.panel._addToPanelBox('dateMenu', dateMenu, -1, Main.panel._rightBox);
                 tray.clockMoved = true;
             }
@@ -2548,7 +2548,7 @@ export default class SystemMonitorExtension extends Extension {
         // restore clock
         if (this.__sm.tray.clockMoved) {
             let dateMenu = Main.panel.statusArea.dateMenu;
-            Main.panel._rightBox.remove_actor(dateMenu.container);
+            Main.panel._rightBox.remove_child(dateMenu.container);
             Main.panel._addToPanelBox('dateMenu', dateMenu, Main.sessionMode.panel.center.indexOf('dateMenu'), Main.panel._centerBox);
         }
         // restore system power icon if necessary
```

and the Clock is properly moved:
Screenshot from 2024-03-08 10-56-53

**Comment by glerroo** [comment]
@marxin, @NVieville Bug resolved, can confirm that is ok.
@mgalgs i think i the solution of .add() is in this commit that remove a monkey patch from St.Layout [environment: Stop patching StBoxLayout](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/c72742486f6735dd25fb20c4f4cbc3a28b1d115f#).

**Comment by mgalgs** [comment]
> @mgalgs i think i the solution of .add() is in this commit that remove a monkey patch from St.Layout [environment: Stop patching StBoxLayout](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/c72742486f6735dd25fb20c4f4cbc3a28b1d115f#).

Got it, thanks.

I think this is mergeable once we get test results on GS 45, verifying no regressions.

**Review by mgalgs — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64)* status: all files reviewed, 2 unresolved discussions (waiting on @glerroo)

___
*[`system-monitor-next@paradoxxx.zero.gmail.com/extension.js` line 265 at r1](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64#-NsRUnZg8NgtejUam8sK:-NsTzNH31WGqRSNstq5g:bg6beej) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/8832b564383ea61b3f81c6972dccc344b518f958/system-monitor-next%40paradoxxx.zero.gmail.com/extension.js#L265)):*
<details><summary><i>Previously, mgalgs (Mitchel Humpherys) wrote…</i></summary><blockquote>

I'm still trying to understand this change. The [GS 46 extension porting guide](https://gjs.guide/extensions/upgrading/gnome-shell-46.html#clutter-container) mentions `Clutter.Container` (`Clutter.Container.add_actor` being of particular interest to us), but I'm not seeing anything about an `.add()` method going away... And I'm actually not even sure which `.add()` method is being called here. I can't find an `.add()` in the `St.BoxLayout` inheritance chain in the gjs docs but I might just be missing it. :grimacing:
</blockquote></details>

Hold on, what about the second argument? Looks like [the old monkey-patched `.add()` method](https://gitlab.gnome.org/GNOME/gnome-shell/-/commit/c72742486f6735dd25fb20c4f4cbc3a28b1d115f) took a second argument of props to copy over, which [`clutter.Actor.add_child()`](https://gjs-docs.gnome.org/clutter13~13/clutter.actor#method-add_child) doesn't seem to do.

**Comment by glerroo** [comment]
I think the second argument is optional, if present assign properties to actor.

```vala
// "monkey patch" in some varargs ClutterContainer methods; we need
// to do this per-container class since there is no representation
// of interfaces in Javascript
function _patchContainerClass(containerClass) {
    // This one is a straightforward mapping of the C method
    containerClass.prototype.child_set = function (actor, props) {
        let meta = this.get_child_meta(actor);
        for (let prop in props)
            meta[prop] = props[prop];
    };

    // clutter_container_add() actually is a an add-many-actors
    // method. We conveniently, but somewhat dubiously, take the
    // this opportunity to make it do something more useful.
    containerClass.prototype.add = function (actor, props) {
        this.add_actor(actor);
        
        if (props)
            this.child_set(actor, props);
    };
}
```
if props is present call this.child_set(actor, props);

**Comment by glerroo** [comment]
In this part there is some problem:
1) I think the smDialog is never opened because smDepsGtop and smDepsNM are always true.
2) I set smDepsGtop to false with the current GS45 version and 
```
Mar 08 22:33:30 fedora gnome-shell[14007]: [system-monitor-next] applet enable from /home/fedora39/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com
Mar 08 22:33:30 fedora gnome-shell[14007]: Extension system-monitor-next@paradoxxx.zero.gmail.com: TypeError: meta is null
                                           
                                           Stack trace:
                                             _patchContainerClass/containerClass.prototype.child_set@resource:///org/gnome/shell/ui/environment.js:45:13
                                             _patchContainerClass/containerClass.prototype.add@resource:///org/gnome/shell/ui/environment.js:54:18
                                             SystemMonitor_smDialog@file:///home/fedora39/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:266:32
                                             enable@file:///home/fedora39/.local/share/gnome-shell/extensions/system-monitor-next@paradoxxx.zero.gmail.com/extension.js:2386:27
                                             _callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:253:38
                                             loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:461:32
                                             async*_loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:759:24
                                             async*_enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:765:48
                                             _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:800:20
                                             async*init@resource:///org/gnome/shell/ui/extensionSystem.js:72:14
                                             _initializeUI@resource:///org/gnome/shell/ui/main.js:303:22
                                             start@resource:///org/gnome/shell/ui/main.js:176:11
                                             @resource:///org/gnome/shell/ui/init.js:12:47
                                             @resource:///org/gnome/shell/ui/init.js:21:20
```

can you verify and make some test?

**Comment by glerroo** [comment]
> @glerroo just to re-iterate, it looks like by moving from `.add()` to `add_child()` we're now losing the second argument (the props to copy to the child). Maybe we need to make a separate call to copy the props (or add an internal helper to do so)? I haven't hunted everything down yet but [`clutter.Container.child_set_property`](https://gjs-docs.gnome.org/clutter13~13/clutter.container#method-child_set_property) looks promising?

@mgalgs Ok I make some test, but smDialog class is never used becase smDepsGtop and smDepsNM are always true. I think we can remove that class.

**Comment by lukedupin** [comment]
I just pulled this PR and everything worked great. I checked the logs for errors, saw none. I clicked through all the menus, flipping things on and off. No issues found.

**Comment by glerroo** [comment]
@mgalgs Clutter.Container was removed from GS46.
[https://gjs.guide/extensions/upgrading/gnome-shell-46.html#clutter-container](https://gjs.guide/extensions/upgrading/gnome-shell-46.html#clutter-container)

**Comment by mgalgs** [comment]
> Ok I make some test, but smDialog class is never used becase smDepsGtop and smDepsNM are always true

@glerroo aaah now I see what you're saying. You're 100% right. I tossed it out and pushed the result. Working fine on my Gnome Shell 46 box, I'll test on 45 a bit later but if anyone else could please test the latest from this PR that would be fantastic!

I don't think there's anything else blocking this other than test results, but please chime in if I'm missing anything.

**Comment by mgalgs** [comment]
Hmm my changes don't seem to be showing up... Currently mobile but I'll check my refs in an hour or so... Stand by...

**Comment by jonnedeprez** [comment]
The PR from @glerroo works fine on my Arch Linux with Gnome 46

**Review by mgalgs — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64)* status: all files reviewed, 1 unresolved discussion (waiting on @glerroo)

**Comment by mgalgs** [comment]
Thanks, @jonnedeprez. Unfortunately, as of the time of your comment the PR branch didn't contain all of the changes :sob: (that was my bad). Can you please re-fetch and try again?

Anyone who wants to test this PR can quickly check it out with:

    git fetch https://github.com/mgalgs/gnome-shell-system-monitor-applet.git +refs/pull/64/head && git checkout FETCH_HEAD

**Review by mgalgs — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @glerroo)

**Comment by glerroo** [comment]
@mgalgs I'm sorry, but at this point I don't understand what I should do.

**Comment by mgalgs** [comment]
@glerroo I just need GS 46 and 45 testing results. I know people have been testing throughout the discussion but I want to make sure the latest changes get tested.

**Comment by mgalgs** [comment]
All right, I've tested on 45 and 46. If someone else could please confirm these test results on the latest version of this PR then we can ship this. :ship: 

    git fetch https://github.com/mgalgs/gnome-shell-system-monitor-applet.git +refs/pull/64/head && git checkout FETCH_HEAD

**Comment by glerroo** [comment]
Ok, i have also tested on Fedora 39 - GS45 and Fedora 40 - GS46 with no error.
I think we can remove also line 34 `import * as ModalDialog from "resource:///org/gnome/shell/ui/modalDialog.js";`

**Review by mgalgs — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/64#-:-Nts0knfAMlSLp-fooSV:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @glerroo)

**Comment by mgalgs** [comment]
Thanks a bunch, @glerroo, and everyone else who provided feedback and test results! I'll get this tagged and shipped to extensions.gnome.org right now, they typically approve within a couple of hours.

**Pull request merged**
