### PR TITLE
Schema rename

### PR DESCRIPTION
**Pull request by mgalgs**
This is an update to #65, please refer to the discussion over there. I had to open a new PR since the branch for that PR lives in @NVieville's repo.

I've only done minimal testing on this, but wanted to get it out there for others to review the approach. I've only tested upgrading from a source install. I haven't tested upgrading from a zipball install (which I assume is how browser installs work). And I've punted on testing system installs due to the fact that our own little private schemas directory isn't there, and I don't want to install our crappy "old" schema to the system-wide directory, and presumably the package manager will have nuked our old one without a trace.

Could some please review the settings migration approach? I also tried a dconf based approach but the code was really ugly and nasty (string deserialization, etc), but maybe I was going about that the wrong way...

Additional testing would also be greatly appreciated!

- - -
This change is [Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/98)

### CODE REVIEW

**Comment by NVieville** [comment]
Hello,

Thank you for your work on this.

I've got some questions, probably naive or noisy, sorry if this is the case.

On the global installation aspect. 
Do you think it would be reasonable to provide the old schema file globally for a while (e.g. installed in `/usr/share/glib-2.0/schemas` directory) and renamed for example `org.gnome.shell.extensions.system-monitor-next-applet.old.gschema.xml` (added the '.old' part in the new name). This could probably (I really don't  know if this could be done) let the migration to be done by the extension itself, because the old and the new schema would be compiled and merged in the global gschemas.compiled file at install time, and then would be accessible by each instance of the extension in user's account. Then further, in a few iterations of the extension, the old file will be removed from the global directory and as the gschemas.compiled file is build at install time, the old reference would be gone.
As said above, I didn't tried this and really don't know if this could work and could be done, but that was my 2 cents from the rpm packager point of view (provide one temporary file while a transition time, then drop it).
As usual, any comment are welcome.
Cordially,


-- 
NVieville

**Review by mgalgs — COMMENTED** [review]
> Reviewed 1 of 10 files at r1, 3 of 9 files at r2, 1 of 7 files at r3, 6 of 7 files at r5, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/98)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @mgalgs)

**Comment by mgalgs** [comment]
I'm feeling pretty good about this. I'll let it marinate for a couple of days in hopes of getting additional testing. Aiming for release later this week.

**Comment by ao2** [comment]
Hi,

I have not followed the issue very closely but I noticed that the [README.md](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/f1847130c8ec007930123ee6344ae3e56b4182d0/README.md?plain=1#L34) file still refers to `gnome-system-monitor` instead of `gnome-system-monitor-next` or `gnome-system-monitor-next-applet`.

Is that expected?

Thanks, Antonio

**Comment by mgalgs** [comment]
@ao2 `gnome-system-monitor` in the prerequisites installation section is actually [the GNOME system monitor app](https://apps.gnome.org/SystemMonitor/), which we launch when you click "System Monitor" from the drop-down menu. So those references are still fine. But thanks for chiming in, it's great to have a lot of eyeballs on this thing.

**Comment by mgalgs** [comment]
All right, this change was actually rejected in EGO review due to the following item in the [EGO Review Guidelines regarding GSettings Schemas](https://gjs.guide/extensions/review-guidelines/review-guidelines.html#gsettings-schemas):

> The Schema XML filename MUST follow pattern of \<schema-id\>.gschema.xml.

I'm not really sure how to proceed with a solution here but have opened [a discussion](https://discourse.gnome.org/t/settings-migration-after-a-schema-rename/25047?u=mgalgs) on the GNOME Discourse to get some ideas.

**Comment by mgalgs** [comment]
Ok, turns out the resolution was simple. I just needed to name the files according to their respective schema IDs. The latest version of the extension on EGO is now using the latest schema ID!

**Comment by NVieville** [comment]
Hello,

Glad to see you sorted out.
I'll package it for Fedora as soon as possible (lots of work at the moment), and see if the migration goes well.
Thank you very much for this.

Cordially,

-- 
NVieville

**Comment by NVieville** [comment]
Hello,

Sorry to reactivate this thread, I wonder how long do you think the actual extension 2 schema files have to be kept to let users migrate to the new schema?

Actually, the bug opened on Fedora bugzilla [1] about schema file conflict with the standard gnome-shell-extension-system-monitor can't be closed because the tip to get a smooth transition for users was to let the old schema file (the one with the conflicting name and the conflicting schema) in place. I guess it's not a so big problem as it supposes that a user wants to install the 2 gnome extensions at the same time, and it's not so common.

One easy way to fix the problem from the Fedora part would be to drop the old schema file in a future version of the package (part of the building package process), letting the drop of the same file from the extension part be delayed. 

Maybe this could lead to some bug reports for the users that don't update/upgrade their systems or packages so often and would have missed the period when both files were present.
One way to help these users to fix the situation would be to suggest them to temporarily download the old schema file in the right directory, rebuild the schema database, relaunch the extension in order to let the smooth migration to operate, then remove the old schema, etc. Maybe this would not be so easy for some users.
Reflection about all these questions stills in progress.

I wonder if you could give your point of view and/or your roadmap on these points.

Regards,


-- 
NVieville

[1] https://bugzilla.redhat.com/show_bug.cgi?id=2268400

**Comment by mgalgs** [comment]
@NVieville I think it's time! I've opened a PR at #120.

**Comment by NVieville** [comment]
@mgalgs Thank you. I've commented on the PR #120.
Concerning "late users" that will have missed the transition period, maybe they should downgrade their extension package to one that embeds the migration code, launch the extension to get their settings migrated to the new schema, then upgrade again the extension package to the last one.

Thank you very much.

Cordially,


-- 
NVieville

**Pull request merged**
