### PR TITLE
extension: Add option to rotate chart labels

### PR DESCRIPTION
**Pull request by rhendric**
### What I tested

- [x] Verified no regressions to existing functionality.
- [x] Tested on the following Gnome Shell versions: 46.2

### Screenshots

before
after

preferences

- - -
This change is [Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/93)

### CODE REVIEW

**Review by mgalgs — CHANGES_REQUESTED** [review]
This is amazing!! :raised_hands: 

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/93#-:-O4DHAe35S5lpxEq7SHM:b-vcx9nj)* status: all files reviewed, 2 unresolved discussions (waiting on @rhendric)

___
*[`system-monitor-next@paradoxxx.zero.gmail.com/extension.js` line 835 at r1](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/93#-O4CwpCN7qNLJw9KH1LI:-O4CwpCO2yeD-FnXXoE4:bqkcaq7) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/55a7b57f1ff71feeade731089ce547434a267e6c/system-monitor-next%40paradoxxx.zero.gmail.com/extension.js#L835)):*
> ```JavaScript
>         GTypeName: 'RotateBin'
>     },
>     class SystemMonitor_RotateBin extends St.Bin {
> ```

Can you please explain the need for this class? Are these overrides based on the original `St.Bin` vfuncs? I'm not too familiar with `St` so I don't know what this is getting us that isn't already supported by `St.Bin`.
___
*[`system-monitor-next@paradoxxx.zero.gmail.com/extension.js` line 954 at r1](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/93#-O4DEt4E1MhAAoF-s9bp:-O4DEt4E1MhAAoF-s9bq:b-ieqopc) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/55a7b57f1ff71feeade731089ce547434a267e6c/system-monitor-next%40paradoxxx.zero.gmail.com/extension.js#L954)):*
> ```JavaScript
>                 this.label.set_rotation_angle(Clutter.RotateAxis.Z_AXIS, -90);
>                 this.label.add_style_class_name('rotated');
>                 return new RotateBin();
> ```

I feel like this should be:

```js
let bin = new RotateBin();
bin.add_child(this.label);
return bin;
```

That way you don't have to do the `if (wrappedLabel !== this.label)` stuff below, although you'll need a new way (maybe `instanceof`?) to determine if the child needs to be removed after the setting is toggled off.

**Comment by rhendric** [comment]
> Can you please explain the need for this class? Are these overrides based on the original St.Bin vfuncs? I'm not too familiar with St so I don't know what this is getting us that isn't already supported by St.Bin.

This widget swaps the horizontal and vertical dimensions of its child. The rendering of the child is rotated with `set_rotation_angle`, but if that's all that happens, the space into which it is painted still has the child's unrotated width and height, which is obviously not ideal for non-square children. All that these overrides are doing is returning the child's preferred width as the bin's preferred height, and vice-versa, and then in the other direction telling the child that it can paint in a box with dimensions flipped from the box in which the bin was told it can paint. Everything else about theme nodes and whatnot comes from the original St.Bin functions, and is generally left in there as a precaution.

> I feel like this should be:
>
>```js
>let bin = new RotateBin();
>bin.add_child(this.label);
>return bin;
>```
> That way you don't have to do the `if (wrappedLabel !== this.label)` stuff below, although you'll need a new way (maybe `instanceof`?) to determine if the child needs to be removed after the setting is toggled off.

The trouble is that the `replace_child` call needs its first argument to still be in the widget tree, and its second argument to be entirely out of it. I tried `replace_child(label, new RotateBin({ child: label }))` at one point and Clutter was not happy with that. So that's why I build the bin empty and only add its child after the `replace_child` call.

**Comment by rhendric** [comment]
I replaced the `RotateBin` class with a layout manager instead; I think that simplifies things nicely!

**Review by mgalgs — CHANGES_REQUESTED** [review]
> I replaced the `RotateBin` class with a layout manager instead; I think that simplifies things nicely!

Indeed, thanks!

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/93#-:-O4MYgN2-FmaqH3tb5gX:bfymg1o)* status: all files reviewed, 2 unresolved discussions (waiting on @rhendric)

___
*[`system-monitor-next@paradoxxx.zero.gmail.com/extension.js` line 834 at r2](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/93#-O4MXdjS9nPY780ZRqRc:-O4MXdjS9nPY780ZRqRd:b2c3m86) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/23abc6be9e1fee2c521365e60d75e01d538e55e1/system-monitor-next%40paradoxxx.zero.gmail.com/extension.js#L834)):*
> ```JavaScript
> // because rotating the child only changes how it is painted, not its geometry.
> // It also moves the bounds on allocation so that the rotated child ends up in
> // the right position.
> ```

I'm still surprised that this is necessary for rotating a widget, but oh well :shrug: Thanks for the comment, this helps.



_Code quote:_
```JavaScript
// This class swaps the vertical and horizontal dimensions of a child element,
// because rotating the child only changes how it is painted, not its geometry.
// It also moves the bounds on allocation so that the rotated child ends up in
// the right position.
```
___
*[`system-monitor-next@paradoxxx.zero.gmail.com/extension.js` line 942 at r2](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/93#-O4MXVIwCjOK7fKQ7UOp:-O4MXVIwCjOK7fKQ7UOq:b-e4uh9r) ([raw file](https://github.com/mgalgs/gnome-shell-system-monitor-applet/blob/23abc6be9e1fee2c521365e60d75e01d538e55e1/system-monitor-next%40paradoxxx.zero.gmail.com/extension.js#L942)):*
> ```JavaScript
>                 this.label.set_rotation_angle(Clutter.RotateAxis.Z_AXIS, -90);
>                 this.label.add_style_class_name('rotated');
>                 this.label_bin.layout_manager = new RotateBinLayout;
> ```

Can we add parens for consistency (`new RotateBinLayout()`)?

**Comment by rhendric** [comment]
Oh, that's troubling! What version GNOME are you running? I can't reproduce on 46.2 but I haven't tried 47 yet.

**Comment by mgalgs** [comment]
Interesting, that was on 45 but looks good on 46!

image

Let's just ship it. 45-ers can just avoid the setting.

**Pull request merged**
