### PR TITLE
Gnome-Shell 43 compatibility update.

### PR DESCRIPTION
**Pull request by Fire-man-x**
Copy commit from  paradoxxxzero/gnome-shell-system-monitor-applet
Close issue: https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/749 and https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/issues/751.

### CODE REVIEW

**Review by knbknb — COMMENTED** [review]
line 1085 of file `./system-monitor@paradoxxx.zero.gmail.com/extension.js` : Just by looking at the code:  shouldn't be this operator `=>`  (fat arrow) be written as `>=` (greater than or equal)?

**Comment by mgalgs** [comment]
> line 1085 of file `./system-monitor@paradoxxx.zero.gmail.com/extension.js` : Just by looking at the code: shouldn't be this operator `=>` (fat arrow) be written as `>=` (greater than or equal)?

I had the same thought. Made a [comment](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/754#pullrequestreview-1163757462) on the PR upstream.

**Comment by mgalgs** [comment]
@Fire-man-x thanks for the fix. However, I want to see what upstream does with it before taking this change. If upstream remains unresponsive we can take this here, but I want to give them a few days at least.

https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/754

**Comment by sibradzic** [comment]
The fix works just fine. @mgalgs I agree that, normally, waiting for upstream is a right thing, but this particular upstream is known for the lack of responsiveness :shrug:

**Comment by mgalgs** [comment]
I'll merge it Friday if upstream still hasn't responded.

**Comment by ZimbiX** [comment]
As a matter of courtesy, you probably should have copied the commits in a way that kept their author as @glerroo so he keeps th credit, e.g. `git cherry-pick <commit>`

**Comment by Fire-man-x** [comment]
@ZimbiX Ok, thanks for advice, next time I will know

**Review by AlbedoTelos — APPROVED** [review]

**Comment by ixevix** [comment]
Nice work! Thanks!

**Comment by 4javier** [comment]
Keep in mind this little change in travis setup to avoid the same CI block of upstream.
https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/757
Gnome 43 landed into Arch Linux official repos, so I think it's just matter of little time to have it in other distros too.
I think it would be better to accept the PR here in the fork without waiting.

**Comment by mgalgs** [comment]
All right, I've integrated the patches from the [upstream PR](https://github.com/paradoxxxzero/gnome-shell-system-monitor-applet/pull/754) (original authorship intact) and [a new build has been submitted](https://github.com/mgalgs/gnome-shell-system-monitor-applet/actions/runs/3406442539/jobs/5665129280#step:3:2849) to extensions.gnome.org. Updates should be landing as soon as the Gnome team reviews the new submission (they're usually pretty quick, < 24 hours).

Thanks, @Fire-man-x, for the PR and everyone else for your input :pray:

**Comment by mgalgs** [comment]
Fixes #25

**Pull request closed without merging**
