### PR TITLE
Preferences  Rewrite.

### LINKED ISSUE #43: Preferences page is a hot mess
The preferences page is currently barely usable, and needs to be seriously cleaned up. It might be nice to just do a full re-write using modern Adwaita widgets (e.g. [Adw.SwitchRow](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.SwitchRow.html), [Adw.ComboRow](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/class.ComboRow.html), etc.).

https://gjs.guide/extensions/development/preferences.html#gsettings

### PR DESCRIPTION
**Pull request by glerroo**
I think is all done and working fine.
The localization must be updated with new strings and new ui files.
This close #43.

- - -
This change is [Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/45)

### CODE REVIEW

**Review by mgalgs — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glerroo)

**Comment by mgalgs** [comment]
This is fantastic... I gave it a quick test drive and a very light code review and everything seems peachy.

I'd appreciate it if someone else could test and/or review as well!

**Review by colin-i — COMMENTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/45)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glerroo)

**Review by mgalgs — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/mgalgs/gnome-shell-system-monitor-applet/45#-:-Ni6LswC7-kO0GjoUhSJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @glerroo)

**Pull request merged**
